name: zakstreamer
description: "Multi-platform streaming app for SR ŻAK PŁ"

publish_to: "none"

environment:
  sdk: ^3.9.2
  flutter: 3.38.5
dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.5
  just_audio_media_kit: ^2.1.0
  cupertino_icons: ^1.0.8
  simple_animations: ^5.2.0
  audio_session: ^0.2.2
  logging: ^1.3.0
  audio_service: ^0.18.18
  get_it: ^9.2.0
  http: ^1.6.0
  html: ^0.15.0
  flutter_local_notifications: ^19.5.0
  scrollable_positioned_list: ^0.3.8
  google_fonts: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"
flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/zak-kropka-niebieska-biale.png"
  min_sdk_android: 16 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/zak-kropka-niebieska-biale.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/zak-kropka-niebieska-biale.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/zak-kropka-niebieska-biale.png"
