name: Build Android AAB and publish to internal testing track

on:
  push:
    tags:
      - "**-alpha*"
    paths-ignore:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - cliff.toml
      - .gitignore
      - .github/**
      - .vscode/**

env:
  FLUTTER_CHANNEL: "stable"
  RUBY_VERSION: "3.3.10"

jobs:
  build_aab:
    name: Build AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: "android"

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "22"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false

      - name: Run Flutter tasks
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version-file: "pubspec.yaml"

      - name: Generate version code
        id: version-code
        run: |
          echo -n "code=$(git rev-list --count ${{ github.ref }})" >> $GITHUB_OUTPUT

      - name: Create service account json
        run: |
          echo -n "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > android/zak-streamer.secret.json

      - name: Create keystore.jks
        run: |
          echo -n "${{ secrets.ANDROID_SIGNING_KEY }}" | base64 --decode > android/keystore.jks

      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties 
          storePassword=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          keyAlias=upload
          storeFile=../keystore.jks
          EOF

      - name: Fetch deps
        run: flutter pub get

      - name: Check flutter environment
        run: flutter doctor

      - name: Build app
        run: |
          echo "Building application with version name ${{ github.ref_name }} and version code ${{ steps.version-code.outputs.code }}"
          flutter build appbundle --build-name ${{ github.ref_name }} --build-number ${{ steps.version-code.outputs.code }}

      - name: Push to internal and alpha testing track
        run: |
          bundle exec fastlane internal version_name:"${{ github.ref_name }}" version_code:${{ steps.version-code.outputs.code }}
          bundle exec fastlane alpha version_name:"${{ github.ref_name }}" version_code:${{ steps.version-code.outputs.code }}
        working-directory: android

      - uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --output CHANGELOG.md

      - uses: ncipollo/release-action@v1
        with:
          bodyFile: "CHANGELOG.md"
          draft: true
          prerelease: true

      - uses: ryancyq/github-signed-commit@v1
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          files: CHANGELOG.md
          commit-message: "docs: update CHANGELOG.md"
          branch-name: main
