# changelog.yml
name: Generate Changelog

on:
  workflow_run:
    workflows: [Build Android AAB and publish to internal testing track]
    types: [completed]
    branches: [main]

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to update CHANGELOG.md

    # Generate changelog for successful build only
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required to check out full git history

      - uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --output CHANGELOG.md

      - uses: ryancyq/github-signed-commit@v1
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          files: CHANGELOG.md
          commit-message: "docs: update CHANGELOG.md"
